<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h2>Sign up  yourself!</h2>
    
    <?php echo $this->tag->form("signup/register"); ?>
    
        <p>
            <label for="name">Name</label>
            <?php echo $this->tag->textField("name"); ?>
        </p>
    
        <p>
            <label for="email">E-Mail</label>
            <?php echo $this->tag->textField("email"); ?>
        </p>
    
        <p>
            <?php echo $this->tag->submitButton("Register"); ?>
        </p>
    
    </form>
    
</body>
</html>
